
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication4
{

using System;
    using System.Collections.Generic;
    
public partial class bilet
{

    public int id_bilet { get; set; }

    public int id_rezerwacja { get; set; }

    public int id_seans { get; set; }

    public int id_miejsce { get; set; }

    public Nullable<bool> weekend { get; set; }



    public virtual miejsce miejsce { get; set; }

    public virtual rezerwacja rezerwacja { get; set; }

    public virtual seans seans { get; set; }

}

}
