
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication4
{

using System;
    using System.Collections.Generic;
    
public partial class film
{

    public film()
    {

        this.seans = new HashSet<seans>();

    }


    public int id_film { get; set; }

    public string tytul { get; set; }

    public string rezyser { get; set; }

    public string opis { get; set; }

    public string gatunek { get; set; }

    public Nullable<double> cena { get; set; }

    public Nullable<int> czas_trwania { get; set; }



    public virtual ICollection<seans> seans { get; set; }

}

}
