
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication4
{

using System;
    using System.Collections.Generic;
    
public partial class klient
{

    public klient()
    {

        this.rezerwacja = new HashSet<rezerwacja>();

    }


    public int id_klient { get; set; }

    public string imie { get; set; }

    public string nazwisko { get; set; }

    public Nullable<double> stala_ulga { get; set; }

    public string numer_telefonu { get; set; }

    public string e_mail { get; set; }



    public virtual ICollection<rezerwacja> rezerwacja { get; set; }

}

}
