
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication4
{

using System;
    using System.Collections.Generic;
    
public partial class miejsce
{

    public miejsce()
    {

        this.bilet = new HashSet<bilet>();

    }


    public int id_miejsce { get; set; }

    public int id_sala { get; set; }

    public Nullable<int> sektor { get; set; }

    public Nullable<int> rzad { get; set; }



    public virtual sala sala { get; set; }

    public virtual ICollection<bilet> bilet { get; set; }

}

}
