
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication4
{

using System;
    using System.Collections.Generic;
    
public partial class rezerwacja
{

    public rezerwacja()
    {

        this.bilet = new HashSet<bilet>();

    }


    public int id_rezerwacja { get; set; }

    public int id_klient { get; set; }

    public Nullable<bool> potwierdzenie { get; set; }



    public virtual klient klient { get; set; }

    public virtual ICollection<bilet> bilet { get; set; }

}

}
