
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication4
{

using System;
    using System.Collections.Generic;
    
public partial class sala
{

    public sala()
    {

        this.miejsce = new HashSet<miejsce>();

        this.seans = new HashSet<seans>();

    }


    public int id_sala { get; set; }

    public Nullable<int> ilosc_miejsc { get; set; }



    public virtual ICollection<miejsce> miejsce { get; set; }

    public virtual ICollection<seans> seans { get; set; }

}

}
