
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication4
{

using System;
    using System.Collections.Generic;
    
public partial class seans
{

    public seans()
    {

        this.bilet = new HashSet<bilet>();

    }


    public int id_seans { get; set; }

    public int id_film { get; set; }

    public int id_sala { get; set; }

    public Nullable<System.DateTime> data { get; set; }

    public Nullable<System.TimeSpan> godzina { get; set; }



    public virtual film film { get; set; }

    public virtual sala sala { get; set; }

    public virtual ICollection<bilet> bilet { get; set; }

}

}
